### ISSUE TITLE
Bug: userProfilePage: Occurs sometimes when going back to userprofile

### ISSUE THREAD

**Issue by PVNagel** [PVNagel/FOPWatchParty#34]
This is the error:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
   at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Result()
   at FOPWatchPartyWebApp.Pages.UserProfile.FetchData() in C:\Users\phili\Documents\Code\MyProjects\FOPWatchParty\FOPWatchPartyWebApp\FOPWatchPartyWebApp\Pages\UserProfile.razor:line 174
   at FOPWatchPartyWebApp.Pages.UserProfile.OnInitializedAsync() in C:\Users\phili\Documents\Code\MyProjects\FOPWatchParty\FOPWatchPartyWebApp\FOPWatchPartyWebApp\Pages\UserProfile.razor:line 162
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by PVNagel** [comment]
Current fix is just to refresh the page
